using System.Globalization;
using PropertyManagement.Application.Abstractions;
using PropertyManagement.Domain.Enums;
using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;
using PdfSharpCore.Pdf.IO;

namespace PropertyManagement.Infrastructure.Services;

/// <summary>
/// PDF form filler. In production this would open a real AcroForm template and fill named fields;
/// here we render a clean fallback PDF using the supplied field map. The contract is identical so
/// real templates can be dropped in by Phase 2.
/// </summary>
public class PdfFormFiller : IPdfFormFiller
{
    public Task<byte[]> PreviewAsync(LtFormType formType, IReadOnlyDictionary<string, string?> fields, CancellationToken ct = default)
        => FillAsync(formType, fields, ct);

    public Task<byte[]> FillAsync(LtFormType formType, IReadOnlyDictionary<string, string?> fields, CancellationToken ct = default)
    {
        using var doc = new PdfDocument();
        doc.Info.Title = FormTitle(formType);
        doc.Info.Author = "PropertyManagement Case Management Platform";

        var page = doc.AddPage();
        var gfx = XGraphics.FromPdfPage(page);
        var titleFont = new XFont("Arial", 16, XFontStyle.Bold);
        var headerFont = new XFont("Arial", 11, XFontStyle.Bold);
        var bodyFont = new XFont("Arial", 10, XFontStyle.Regular);
        var smallFont = new XFont("Arial", 8, XFontStyle.Italic);

        var margin = 50.0;
        var y = margin;

        gfx.DrawString("STATE OF NEW JERSEY", headerFont, XBrushes.Black, new XPoint(margin, y));
        y += 16;
        gfx.DrawString("SPECIAL CIVIL PART — LANDLORD/TENANT SECTION", headerFont, XBrushes.Black, new XPoint(margin, y));
        y += 24;
        gfx.DrawString(FormTitle(formType), titleFont, XBrushes.Black, new XPoint(margin, y));
        y += 24;
        gfx.DrawLine(XPens.Black, margin, y, page.Width - margin, y);
        y += 16;

        foreach (var kvp in fields)
        {
            var label = ToLabel(kvp.Key);
            var value = kvp.Value ?? string.Empty;
            gfx.DrawString($"{label}:", headerFont, XBrushes.Black, new XPoint(margin, y));
            y += 14;
            foreach (var line in WrapText(value, 95))
            {
                gfx.DrawString(line, bodyFont, XBrushes.Black, new XPoint(margin + 12, y));
                y += 13;
                if (y > page.Height - margin - 40)
                {
                    page = doc.AddPage();
                    gfx.Dispose();
                    gfx = XGraphics.FromPdfPage(page);
                    y = margin;
                }
            }
            y += 8;
        }

        gfx.DrawLine(XPens.Gray, margin, page.Height - margin - 24, page.Width - margin, page.Height - margin - 24);
        gfx.DrawString(
            $"Generated by PropertyManagement on {DateTime.UtcNow:u} — Form ID: {formType}",
            smallFont, XBrushes.Gray, new XPoint(margin, page.Height - margin - 10));

        gfx.Dispose();

        using var ms = new MemoryStream();
        doc.Save(ms, false);
        return Task.FromResult(ms.ToArray());
    }

    public Task<byte[]> MergeAsync(IEnumerable<byte[]> pdfs, CancellationToken ct = default)
    {
        using var output = new PdfDocument();
        foreach (var bytes in pdfs)
        {
            using var ms = new MemoryStream(bytes);
            using var input = PdfReader.Open(ms, PdfDocumentOpenMode.Import);
            for (int i = 0; i < input.PageCount; i++)
            {
                output.AddPage(input.Pages[i]);
            }
        }
        using var outMs = new MemoryStream();
        output.Save(outMs, false);
        return Task.FromResult(outMs.ToArray());
    }

    private static string FormTitle(LtFormType t) => t switch
    {
        LtFormType.VerifiedComplaint => "Verified Complaint — Residential Landlord/Tenant",
        LtFormType.Summons => "Summons — Landlord/Tenant",
        LtFormType.CertificationByLandlord => "Certification by Landlord",
        LtFormType.CertificationByAttorney => "Certification by Landlord's Attorney",
        LtFormType.CertificationOfLeaseAndRegistration => "Certification of Lease and Registration Statement",
        LtFormType.LandlordCaseInformationStatement => "Landlord Case Information Statement (LCIS)",
        LtFormType.RequestForResidentialWarrantOfRemoval => "Request for Residential Warrant of Removal",
        _ => t.ToString()
    };

    private static string ToLabel(string key)
    {
        var s = System.Text.RegularExpressions.Regex.Replace(key, "([A-Z])", " $1").Trim();
        return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(s.ToLowerInvariant());
    }

    private static IEnumerable<string> WrapText(string s, int maxChars)
    {
        if (string.IsNullOrEmpty(s)) yield return string.Empty;
        else
        {
            for (int i = 0; i < s.Length; i += maxChars)
                yield return s.Substring(i, Math.Min(maxChars, s.Length - i));
        }
    }
}
